### ISSUE TITLE
Fails to parse cookies

### ISSUE THREAD

**Issue by EmperorPenguin18** [Sorrow446/MUR_Go#2]
When running I get this error:
```
panic: runtime error: index out of range [3] with length 1

goroutine 1 [running]:
main.parseCookies()
	/home/sebastien/git/MUR_Go/main.go:129 +0x832
main.init.0()
	/home/sebastien/git/MUR_Go/main.go:363 +0x1bb
exit status 2
```
Here is the cookies file I'm using:
[cookies.txt](https://github.com/Sorrow446/MUR_Go/files/7975680/cookies.txt)

**Comment by Sorrow446** [comment]
Hey. The tool expects Netscape cookies, not JSON.

**Comment by mr-iglesias** [comment]
I can't download anything, I always get the same text:

Failed to get comic metadata. json: cannot unmarshal array into Go struct field .data.results.issue_meta.purchase_data of type struct { DigitalPrice float64 "json:\"digital_price\""; StoreURLMobile string "json:\"store_url_mobile\"" }

**Comment by Sorrow446** [comment]
I wanna clean the code up and fix the above issue. If you can lend me your account, please message me.
https://www.reddit.com/user/Sorrow446
Sorrow#6826

**Comment by Evoley** [comment]
I'm getting the same issue even with Netscape cookies
